### PR TITLE
Fix Spacing for `setrep` parameters

### LINKED ISSUE #82: `-setrep` threw `Wrong format` error possibly due to the double-whitespace between the arguments
## Describe the bug
Running `-setrep @Daniel Nguyen | 96  60` resulted in `Wrong format. The correct format is setRep @username repNumber`. 

### To Reproduce

0. Sign in as an administrator
1. Go to a channel in the VAIT discord where this bot is enabled
2. Type `-setrep @Daniel Nguyen | 96  60`
3. See the error `Wrong format. The correct format is setRep @username repNumber`

### Expected behavior

It was not clear why the command resulted in this error. The initially hypothesised reason was the double-whitespace between `@Daniel Nguyen | 96` and `60`. Double-whitespace can be hard to detect in a non-monospace typeface, especially the default fonts in Discord.

### PR DESCRIPTION
**Pull request by samhwang**
## Description
This will provide an additional step in checking for empty words after splitting by spaces, thus in turn will prevent an error occurs when we have an extra space between the parameters

## Related Issue
This will close #82 

## How Has This Been Tested?
- The test was ran on our Bot Testing Server
- Commands typed: `;;;;setrep @Sam 0` and `;;;;setrep @Sam  0`. Both are behaving the same (setting my own rep back to 0).

## Screenshots (if appropriate):
Screen Shot 2022-03-13 at 1 13 16 am

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/commands/reputation/setReputation.ts [hunk 1]
```diff
@@ -20,7 +20,9 @@ export const setReputation = async (msg: Message) => {
   if (!discordUser) return; // return if user not found
   if (discordUser.bot) return; // return if mention bot
 
-  const splittedMessage = msg.content.split(' ');
+  const splittedMessage = msg.content
+    .split(' ')
+    .filter((word) => word.length > 0);
```
Comment (tklarryonline) [inline src/commands/reputation/setReputation.ts:25]: You can also do the following to get rid of all spaces in between words.

```suggestion
  const splittedMessage = msg.content.split(/\s+/);
```

**Review by tklarryonline — APPROVED** [review]
